cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('pages/', include('django.contrib.flatpages.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    
    price  = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created  = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
    
    
    
    

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.Select(attrs={'class': 'custom-select ml-1'}))
    override = forms.BooleanField(initial=False, required=False, widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart 
from .forms import CartAddProductForm
from django.conf import settings
# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    print(request.session.modified)
    print(request.session.get(settings.CART_SESSION_ID))
    return render(request, 'cart/detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
# Create your views here.

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    return render(request, 'shop/product/detail.html', {
        'product': product,
        'cart_product_form': cart_product_form
    })

templates/cart/detail.html
{% extends 'shop/base.html' %}

{% block content %}
    <h1>lolo is best</h1>
    {% for item in cart %}
    {{ item.product.name }}
    {{ item.quantity }}
    {% empty %}
    <h2>No item, empty.</h2>
    {% endfor %}
{% endblock %}

templates/shop/base.html
{% load static %}
{% load flatpages %}
{% get_flatpages as flatpages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Viaoda+Libre&display=swap" rel="stylesheet"> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
    <title>{% block title %}My shop{% endblock %}</title>
    <style>
        body {
            font-family: 'Viaoda Libre', cursive;
        }

    </style>
</head>
<body>
    <header class="navbar navbar-expand-md navbar-light bg-white">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>

            {% for page in flatpages %}
                <li class="nav-item"><a href="/pages{{ page.url }}" class="nav-link">{{ page.title }}</a></li>
            {% endfor %}
</ul>
        </ul>

    </header>


    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card p-2 m-2">
                    Your card is empty
                </div>
            </div>
        </div>

        <div class="">

            {% block content %}
            {% endblock %}

        </div>

    </div>
    
</body>
</html>

templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="row p-2 mt-2">
        <div class="col-8">
            <div class="row">
                <div class="col-6 p-2">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.png' %}{% endif %}" alt="{{ product.name }}" class="img-fluid img-thumbnail" width="320" height="260">
                </div>
                <div class="col-6">
                    <h1>{{ product.name }}</h1>
                    <h2 class="h6">
                        <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
                    </h2>
                    <p>${{ product.price }}</p>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post" class="form-inline">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ cart_product_form }}
                        </div>
                        <input type="submit" value="Add to cart" class="btn btn-success ml-3">
                    </form>
                    <p>
                        {{ product.description|linebreaks }}
                    </p>
                </div>
            </div>
            
        </div>
    </div>

{% endblock %}

templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div class="row p-2 mt-2">
        <div class="col-4">
            <h3>Categories</h3>            
            <ul>
                <li {% if not category %}class='selected'{% endif %}>
                    <a href="{% url 'shop:product_list' %}">All</a>
                </li>
                {% for c in categories %}
                    <li {% if category.slug == c.slug %}class='selected' {% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-8">
            <h1> {% if category %}{{ category.name }}{% else %}Products {% endif %}</h1>
            <div class="row">
                {% for p in products %}
                <div class="col-4">
                    <a href="{{ p.get_absolute_url }}">
                        <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static 'img/noimage.png' %}{% endif %}" alt="{{ p.name }}" class="border rounded p-1" width="195" height="150">
                    </a>
                    <br>
                    <a href="{{ p.get_absolute_url }}">{{ p.name }}</a>
                    <br>
                    ${{ p.price }}
                </div>

                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}